back to normal

diff --git a/.github/workflows/google-cloudrun-docker.yml b/.github/workflows/google-cloudrun-docker.yml
--- a/.github/workflows/google-cloudrun-docker.yml
+++ b/.github/workflows/google-cloudrun-docker.yml
@@ -1,114 +1,114 @@
-# This workflow build and push a Docker container to Google Artifact Registry
-# and deploy it on Cloud Run when a commit is pushed to the "main"
-# branch.
-#
-# To configure this workflow:
-#
-# 1. Enable the following Google Cloud APIs:
-#
-#    - Artifact Registry (artifactregistry.googleapis.com)
-#    - Cloud Run (run.googleapis.com)
-#    - IAM Credentials API (iamcredentials.googleapis.com)
-#
-#    You can learn more about enabling APIs at
-#    https://support.google.com/googleapi/answer/6158841.
-#
-# 2. Create and configure a Workload Identity Provider for GitHub:
-#    https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation.
-#
-#    Depending on how you authenticate, you will need to grant an IAM principal
-#    permissions on Google Cloud:
-#
-#    - Artifact Registry Administrator (roles/artifactregistry.admin)
-#    - Cloud Run Developer (roles/run.developer)
-#
-#    You can learn more about setting IAM permissions at
-#    https://cloud.google.com/iam/docs/manage-access-other-resources
-#
-# 3. Change the values in the "env" block to match your values.
+# # This workflow build and push a Docker container to Google Artifact Registry
+# # and deploy it on Cloud Run when a commit is pushed to the "main"
+# # branch.
+# #
+# # To configure this workflow:
+# #
+# # 1. Enable the following Google Cloud APIs:
+# #
+# #    - Artifact Registry (artifactregistry.googleapis.com)
+# #    - Cloud Run (run.googleapis.com)
+# #    - IAM Credentials API (iamcredentials.googleapis.com)
+# #
+# #    You can learn more about enabling APIs at
+# #    https://support.google.com/googleapi/answer/6158841.
+# #
+# # 2. Create and configure a Workload Identity Provider for GitHub:
+# #    https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation.
+# #
+# #    Depending on how you authenticate, you will need to grant an IAM principal
+# #    permissions on Google Cloud:
+# #
+# #    - Artifact Registry Administrator (roles/artifactregistry.admin)
+# #    - Cloud Run Developer (roles/run.developer)
+# #
+# #    You can learn more about setting IAM permissions at
+# #    https://cloud.google.com/iam/docs/manage-access-other-resources
+# #
+# # 3. Change the values in the "env" block to match your values.
 
-name: 'Build and Deploy to Cloud Run'
+# name: 'Build and Deploy to Cloud Run'
 
-on:
-  push:
-    branches:
-      - 'main'
-    paths-ignore:
-      - 'docs/main.js'
+# on:
+#   push:
+#     branches:
+#       - 'main'
+#     paths-ignore:
+#       - 'docs/main.js'
 
-env:
-  PROJECT_ID: 'my-reflex-app'
-  REGION: 'us-central1'
-  SERVICE: 'reflex-backend'
-  FRONTEND_DIR: 'docs'
-  WORKLOAD_IDENTITY_PROVIDER: 'projects/639974523808/locations/global/workloadIdentityPools/github/providers/my-repo' 
-jobs:
-  deploy:
-    runs-on: 'ubuntu-latest'
+# env:
+#   PROJECT_ID: 'my-reflex-app'
+#   REGION: 'us-central1'
+#   SERVICE: 'reflex-backend'
+#   FRONTEND_DIR: 'docs'
+#   WORKLOAD_IDENTITY_PROVIDER: 'projects/639974523808/locations/global/workloadIdentityPools/github/providers/my-repo' 
+# jobs:
+#   deploy:
+#     runs-on: 'ubuntu-latest'
 
-    permissions:
-      contents: 'write'
-      id-token: 'write'
+#     permissions:
+#       contents: 'write'
+#       id-token: 'write'
 
-    steps:
-      - name: 'Checkout'
-        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4
+#     steps:
+#       - name: 'Checkout'
+#         uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4
 
-      # Configure Workload Identity Federation and generate an access token.
-      #
-      # See https://github.com/google-github-actions/auth for more options,
-      # including authenticating via a JSON credentials file.
-      - id: 'auth'
-        name: 'Authenticate to Google Cloud'
-        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2' # google-github-actions/auth@v2
-        with:
-          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
+#       # Configure Workload Identity Federation and generate an access token.
+#       #
+#       # See https://github.com/google-github-actions/auth for more options,
+#       # including authenticating via a JSON credentials file.
+#       - id: 'auth'
+#         name: 'Authenticate to Google Cloud'
+#         uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2' # google-github-actions/auth@v2
+#         with:
+#           workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
 
-      # BEGIN - Docker auth and build
-      #
-      # If you already have a container image, you can omit these steps.
-      - name: 'Docker Auth'
-        uses: 'docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567' # docker/login-action@v3
-        with:
-          username: 'oauth2accesstoken'
-          password: '${{ steps.auth.outputs.auth_token }}'
-          registry: '${{ env.REGION }}-docker.pkg.dev'
+#       # BEGIN - Docker auth and build
+#       #
+#       # If you already have a container image, you can omit these steps.
+#       - name: 'Docker Auth'
+#         uses: 'docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567' # docker/login-action@v3
+#         with:
+#           username: 'oauth2accesstoken'
+#           password: '${{ steps.auth.outputs.auth_token }}'
+#           registry: '${{ env.REGION }}-docker.pkg.dev'
 
-      - name: 'Build and Push Container'
-        run: |-
-          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}"
-          docker build -f Dockerfile --tag "${DOCKER_TAG}" .
-          docker push "${DOCKER_TAG}"
+#       - name: 'Build and Push Container'
+#         run: |-
+#           DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}"
+#           docker build -f Dockerfile --tag "${DOCKER_TAG}" .
+#           docker push "${DOCKER_TAG}"
           
-      - id: 'deploy'
-        name: 'Deploy to Cloud Run'
+#       - id: 'deploy'
+#         name: 'Deploy to Cloud Run'
 
-        # END - Docker auth and build
+#         # END - Docker auth and build
 
-        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17' # google-github-actions/deploy-cloudrun@v2
-        with:
-          service: '${{ env.SERVICE }}'
-          region: '${{ env.REGION }}'
-          project_id: '${{ env.PROJECT_ID }}'
-          # NOTE: If using a pre-built image, update the image name below:
+#         uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17' # google-github-actions/deploy-cloudrun@v2
+#         with:
+#           service: '${{ env.SERVICE }}'
+#           region: '${{ env.REGION }}'
+#           project_id: '${{ env.PROJECT_ID }}'
+#           # NOTE: If using a pre-built image, update the image name below:
 
-          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}'
-      - name: 'Build and Run Frontend Container'
-        run: |-
-          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}"
-          docker build -f 'web.Dockerfile' --tag 'reflex-frontend' .
-          docker run --rm -e API_URL="${{ steps.deploy.outputs.url }}" -v "$PWD/docs":/app/docs -v "$PWD":/app/workspace -w /app/workspace reflex-frontend /bin/bash -c "mkdir -p docs && cp -r .web/build/client/* docs/"  
-      # - name: 'Write runtime config for frontend'
-      #   run: |-
-      #     CLOUD_RUN_URL="${{ steps.deploy.outputs.url }}"
-      #     if [ -z "$CLOUD_RUN_URL" ]; then
-      #       echo "No Cloud Run URL; aborting"
-      #       exit 1
-      #     echo "window.BACKEND_URL = \"$CLOUD_RUN_URL\";" > docs/config.js
-      - name: 'Commit & Push to GitHub Pages'
-        run: |-
-          git config user.name "paulmurphyy"
-          git config user.email "luappanda@gmail.com"
-          git add docs && git diff --cached --quiet ||
-          git commit -m "Update backend URL to $CLOUD_RUN_URL" || echo "No changes to commit"
-          git push origin main
+#           image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}'
+#       - name: 'Build and Run Frontend Container'
+#         run: |-
+#           DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}"
+#           docker build -f 'web.Dockerfile' --tag 'reflex-frontend' .
+#           docker run --rm -e API_URL="${{ steps.deploy.outputs.url }}" -v "$PWD/docs":/app/docs -v "$PWD":/app/workspace -w /app/workspace reflex-frontend /bin/bash -c "mkdir -p docs && cp -r .web/build/client/* docs/"  
+#       # - name: 'Write runtime config for frontend'
+#       #   run: |-
+#       #     CLOUD_RUN_URL="${{ steps.deploy.outputs.url }}"
+#       #     if [ -z "$CLOUD_RUN_URL" ]; then
+#       #       echo "No Cloud Run URL; aborting"
+#       #       exit 1
+#       #     echo "window.BACKEND_URL = \"$CLOUD_RUN_URL\";" > docs/config.js
+#       - name: 'Commit & Push to GitHub Pages'
+#         run: |-
+#           git config user.name "paulmurphyy"
+#           git config user.email "luappanda@gmail.com"
+#           git add docs && git diff --cached --quiet ||
+#           git commit -m "Update backend URL to $CLOUD_RUN_URL" || echo "No changes to commit"
+#           git push origin main
